parameters:

    #
    # Factories
    #
    elcodi.core.tax.factory.tax.class: Elcodi\Component\Tax\Factory\TaxFactory
    elcodi.core.tax.factory.tax_group.class: Elcodi\Component\Tax\Factory\TaxGroupFactory
