services:

    #
    # Object Managers
    #
    elcodi.object_manager.tax:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.tax.entity.tax.class% ]

    elcodi.object_manager.tax_group:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.tax.entity.tax_group.class% ]
