services:

    #
    # Repositories
    #

    #
    # Repository for entity tax
    #
    elcodi.repository.tax:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.tax.entity.tax.class% ]

    #
    # Repository for entity tax group
    #
    elcodi.repository.tax_group:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.tax.entity.tax_group.class% ]
